### PR TITLE
fix: use context schema

### LINKED ISSUE #16: Cannot extend cart schema
In the transformAndValidateCart mutation the cart schema is loaded directly from file as `import { Cart as CartSchema } from "../simpleSchemas.js";`. It makes it impossible to extend the cart schema as the validation fails. The schema should be retrieved from the context as follows: `const CartSchema = context.simpleSchemas.Cart;`

### PR DESCRIPTION
**Pull request by MohanNarayana**
Signed-off-by: Mohan Narayana <mohan.narayana@mailchimp.com>

Resolves #16
Impact: **minor**
Type: **bugfix**

## Issue
Schema is directly referenced from simpleSchema.js which could cause validation failure upon extending schema.

## Solution
The schema should be retrieved from the context

## Testing
1. Add items to cart, change quantity and delete. All actions should work without error.

### CODE REVIEW

**Review by delagroove — APPROVED** [review]

**Comment by brent-hoover** [comment]
@MohanNarayana As we discussed I would have really liked to see a test for this. Also would like to understand how you validated that this worked

File: src/mutations/transformAndValidateCart.js [hunk 1]
```diff
@@ -15,6 +14,7 @@ const logCtx = { name: "cart", file: "transformAndValidateCart" };
  * @returns {undefined}
  */
 export default async function transformAndValidateCart(context, cart) {
+  const cartSchema = context.simpleSchemas.Cart;
```
Comment (brent-hoover) [inline src/mutations/transformAndValidateCart.js:17]: Generally we should always favor destructuring. Not sure why linting didn't catch that

**Comment by MohanNarayana** [comment]
@zenweasel The check I was doing in the first place was incorrect. I was looking at what validate() returns, which is always undefined but it handles the errors internally. So no issues with schema or validating. I will write up a test for this script.
